#!/bin/sh
LC_ALL=C
unset SHELL

usage() {
    echo "Usage: bead command [options]

Commands:
    test -- test a single submission
    bulk -- test all incoming submissions (continuously)
"
    exit 1
}

[ $# -lt 1 ] && usage

SCRIPT_PATH=$(realpath $0)
SCRIPT_PREFIX=$(dirname ${SCRIPT_PATH})
SCRIPT_MODULES="${SCRIPT_PREFIX}/modules"

CMD=$1
shift

case ${CMD} in
    test)
        exec env -i PATH=${PATH} /bin/sh ${SCRIPT_MODULES}/test.sh $@
        ;;
    bulk)
        exec env -i PATH=${PATH} /bin/sh ${SCRIPT_MODULES}/bulk.sh $@
        ;;
    help)
        usage
        ;;
    *)  echo "Unknown command: ${CMD}"
        usage
        ;;
esac
